version: "3.8"

services:
    marketplace:
        build:
            context: ./marketplace
        environment:
            RECOMMENDATIONS_HOST: recommendations
        # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
        #                   -t marketplace --secret id=ca.key,src=ca.key
        image: marketplace
        container_name: marketplace_grpc_app
        networks:
            - microservices
        ports:
            - 5000:5000

    recommendations:
        build:
            context: ./recommendations
        # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
        #                   -t recommendations --secret id=ca.key,src=ca.key
        image: recommendations
        container_name: recommendations_grpc_app
        networks:
            - microservices

networks:
  microservices:
    name: microservices
    driver: bridge
